apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: functions.projectriff.io
spec:
  scope: Namespaced
  group: projectriff.io
  version: v1alpha1
  names:
    kind: Function
    plural: functions
    singular: function

